spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:                    # 数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sdgs_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# MyBatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志输出

server:
  tomcat:
    max-swallow-size: -1

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t9d2TSnVvjL6Sk4Yjfn
    access-key-secret: kBZm6FdK1lgZNnqdGgyesgUxSxceJ4
    bucket-name: sdgs-images-shanghai